name: pdp_foundation
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+4

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8


  # code
  dio: ^5.8.0+1
  intl: ^0.20.2
  dartz: ^0.10.1
  retrofit: ^4.4.1
  shared_preferences: ^2.5.1
  flutter_secure_storage: ^9.2.2
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.3.0

  # core
  flutter_facebook_auth: ^7.1.1
  sign_in_with_apple: ^6.1.4
  google_sign_in: ^6.2.2
  flutter_tts: ^4.2.1
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.2
  flutter_launcher_icons: ^0.14.3
  latlong2: ^0.9.1
  pretty_dio_logger: ^1.4.0

  # ui
  loading_animation_widget: ^1.3.0
  google_fonts: ^6.2.1
  dropdown_button2: ^2.3.9
  percent_indicator: ^4.2.4
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.0.17
  toastification: ^2.1.0
  flutter_map: ^8.0.0
  skeletonizer: ^1.4.3
  cached_network_image: ^3.4.1

  # models
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  faker: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.7
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.3

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/
    - assets/brand/


  fonts:
    - family: ClashDisplay
      fonts:
        - asset: assets/fonts/ClashDisplay-Extralight.ttf
          weight: 200
        - asset: assets/fonts/ClashDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/ClashDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/ClashDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/ClashDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/ClashDisplay-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/brand/logo.png"  # ✅ Make sure this file has NO transparency
  adaptive_icon_background: "#FFFFFF"  # (Optional) Ensures a solid background



